## 6.3.1 Entendiendo los problemas con callbacs simples.

Usamos codigo asyncronico por que no queremos bloquear la ejecucion de nuestra aplicacion ( de este modo no desalentar 
a nuestros usuarios ) mientras se ejecutan tareas de larga duracion. Actualmente, resolvemos este problema con callbacks: 
Para una tarea de larga duracion proveemos una funcion, un callback que es invocado cuando la tarea finalmente se haya 
hecho.
Por ejemplo, fetching un archivo JSON desde un servidor en una tarea de larga duracion, durante la cual no queremos 
que la aplicacion no sea responsiva por nuestros usuarios. Por lo tanto, proveemos un callback el cual vamos a invocar 
cuando el task haya terminado.

```
getJSON("data/ninjas.json", function() {
    /*HANDLE RESULTS*/
});
```
Naturalmente, durante una tarea de larga duracion, errores pueden ocurrir. Y el problema con los callbacks es que usted 
no puede utilizar built-in constructores de el lenguaje, tales como try-catch, de la siguiente manera.

```
try {
    getJSON("data/ninjas.json", function() {
        /*HANDLE RESULTS*/
    });
} catch(e){/*HANDLE ERRORS*/}
```
Esto pasa por que el codigo que esta haciendo invocado por el callback usualmente no es ejecutado en el mismo paso de 
el loop del evento como el codigo empieza tareas de larga duracion (usted va a ver que significa esto cuando usted 
aprenda hacer de el evento loop en el capitulo 13).

Como consecuencia, los errores usualmente se pierden. Muchas librerias, por lo tanto, definen sus propias convenciones 
para reportar errores. Por ejemplo, en el caso de Node.js, los callbacks habitualmente tiene dos argumentos, err y data, 
donde *err* va a hacer un valor *non-null* si un error ocurre en algun lugar a lo largo del camino. Esto nos lleva al 
primer problema con callbacks: *dificil para manejar errores*.

Despues de que hayamos de haber realizado una tarea de larga duracion, a menudo queremos hacer algo con la data obtenida. 
Esto nos puede llevar a empear otro task de larga duracion, que eventualmente puede disparar otra tarea de larga duracion, 
y asi sucesivamente, llevandonos a una serie de pasos interdependientes, asyncronicos, passos de callbacks procesados.
Por ejemplo, si queremos ejecutar un plan astuto para encontrar a todos los ninjas a nuestra disposicion, obtener la 
localizacion del primer ninja, y enviarle algunas ordenes, terminanos col algo como esto.

```
getJSON("data/ninjas.json", function(err, ninjas){
	getJSON(ninjas[0].location, function(err, locationInfo){
		sendOrder(locationInfo, function(err, status){
			/*Process status*/
		})
	})
});
```
Usted probablemente a termiando asi un par de veces, con una estructura similar -- un monton de callbacks anidados que 
represetan pasos que tenemos que hacer. Usted talvez alla notado que este codigo sea dificil de comprender, insertando 
nuevos pasos es un dolor de cabeza, y el manejo de errores, complica el codigo significantemente. Usted obtiene esta 
"Piramide de perdicion" que mantiene credindo y es difici de manejar. Esto nos lleva a un segundo problema con los 
callbaks: realizar secuencia de pasos es complicado.

Algunas veces, los pasos que tenemos que realizar para obtener un resultado final no depende entre ellos, entonces no 
tenemos que hacer en secuencia. En vez de eso, para salvar valiosos milisegundos. lo podemos hacer en paralelo. Por ejemplo 
si queremos hacer un plan en movimiento que requiera saber cuales ninjas tenemos a nuestra disposicion, el plan mismo, 
y obtener la localizacion donde nuestro plan se va a llevar a cabo, podemos tomar ventaja de el metodo get de jQuery
y escribir algo como esto.
```
$.get("data/ninjas.json", function(err, data){
	if(err) { processError(err); return; }
	ninjas = data;
	actionItemArrived();
});

$.get("data/mapInfo.json", function(err, data){
	if(err) { processError(err); return; }
	mapInfo = data;
	actionItemArrived();
});

$.get("plan.json", function(err, data) {
	if(err) { processError(err); return; }
	plan = data;
	actionItemArrived ();
});
function actionItemArrived(){
	if(ninjas != null && mapInfo != null && plan != null){
		console.log("The plan is ready to be set in motion!");
	}
}
function processError(err){
	alert("Error", err)
}
```








